[client]
toolbarMode = "viewer"

[theme]
primaryColor = "#155285"

# The radius used as basis for the corners of most UI elements. This can
# be one of the following: "none", "small", "medium", "large", "full",
# or the number in pixels or rem. For example, you can use "10px",
# "0.5rem", or "2rem". To follow best practices, use rem instead of
# pixels when specifying a numeric size.
baseRadius = "0.5rem"

# The color of the border around elements.
borderColor = "#0f3a5d"

font = "roboto"
